# Generated by Django 4.0 on 2022-01-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='triggerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('direction', models.CharField(max_length=30)),
                ('ratio', models.CharField(max_length=30)),
                ('upper', models.CharField(max_length=30)),
                ('lower', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('profit', models.CharField(max_length=30)),
            ],
        ),
    ]
