# Generated by Django 4.0 on 2022-01-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerdata',
            name='priceEntered',
            field=models.CharField(default='0', max_length=30),
            preserve_default=False,
        ),
    ]
