# Generated by Django 4.0 on 2022-01-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_triggerdata_priceentered'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerdata',
            name='currentPL',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
