# Generated by Django 4.0 on 2022-02-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_triggerdata_currentpl'),
    ]

    operations = [
        migrations.CreateModel(
            name='patternData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('direction', models.CharField(max_length=30)),
                ('pattern', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
